# setup-env.ps1
# Reads .env and generates assets/js/firebase-config.js
# Run: powershell -ExecutionPolicy Bypass -File setup-env.ps1

$envFile = ".env"
$outputFile = "assets\js\firebase-config.js"

if (-not (Test-Path $envFile)) {
    Write-Host "ERROR: .env file not found." -ForegroundColor Red
    Write-Host "Copy .env.example to .env and fill in your Firebase keys." -ForegroundColor Yellow
    exit 1
}

# Parse .env into a hashtable
$config = @{}
Get-Content $envFile | ForEach-Object {
    $line = $_.Trim()
    if ($line -match '^\s*#' -or $line -eq '') { return }
    $parts = $line -split '=', 2
    if ($parts.Length -eq 2) {
        $config[$parts[0].Trim()] = $parts[1].Trim()
    }
}

# Validate required keys
$required = @(
    'FIREBASE_API_KEY',
    'FIREBASE_AUTH_DOMAIN',
    'FIREBASE_PROJECT_ID',
    'FIREBASE_STORAGE_BUCKET',
    'FIREBASE_MESSAGING_SENDER_ID',
    'FIREBASE_APP_ID'
)

$missing = $required | Where-Object { -not $config.ContainsKey($_) -or $config[$_] -match '^your_' }
if ($missing.Count -gt 0) {
    Write-Host "ERROR: Missing or placeholder values in .env:" -ForegroundColor Red
    $missing | ForEach-Object { Write-Host "  - $_" -ForegroundColor Yellow }
    exit 1
}

# Generate firebase-config.js
$output = @"
// AUTO-GENERATED by setup-env.ps1 — DO NOT EDIT MANUALLY
// This file is gitignored. Run setup-env.ps1 to regenerate.
window.ZAPLIN_FIREBASE_CONFIG = {
  apiKey: '$($config['FIREBASE_API_KEY'])',
  authDomain: '$($config['FIREBASE_AUTH_DOMAIN'])',
  projectId: '$($config['FIREBASE_PROJECT_ID'])',
  storageBucket: '$($config['FIREBASE_STORAGE_BUCKET'])',
  messagingSenderId: '$($config['FIREBASE_MESSAGING_SENDER_ID'])',
  appId: '$($config['FIREBASE_APP_ID'])',
};
"@

Set-Content -Path $outputFile -Value $output -Encoding UTF8
Write-Host "firebase-config.js generated successfully at: $outputFile" -ForegroundColor Green
